updated configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,75 +4,59 @@ CC='gcc'
 # remove old output files
 rm -f config.mk
 
+
 have_lib() {
     echo -n "checking for $1 ... "
-    if ! pkg-config "--exists" $1 2>/dev/null; then
-        echo "no"
-        return 1
-    fi
-    echo "yes"
-    return 0
+    pkg-config "--exists" $1 2>/dev/null
+    test $? -ne 0 && echo "no" && return 1
+    echo "yes" && return 0
 }
 
 have_header() {
     echo -n "checking for $1 ... "
-    echo "#include <$1>" | $CC $CPPFLAGS -E -xc -o /dev/null - 2>/dev/null
-    if test $? -ne 0; then 
-        echo 'no'
-        return 1
-    fi
-    echo 'yes'
-    return 0
+    echo "#include <$1>" | $CC $CFLAGS -E -xc -o /dev/null - 2>/dev/null
+    test $? -ne 0 && echo "no" && return 1
+    echo "yes" && return 0
 }
 
 assert_header() {
-    if ! have_header "$1"; then
-        echo "missing header: $1"
-        exit 1
-    fi
+    have_header "$1" && return 0
+    echo "missing header: $1" && exit 1
 }
 
 assert_lib() {
-    if ! have_lib "$1"; then 
-        echo "missing lib: $1"
-        exit 1
-    fi
+    have_lib "$1" && return 0 
+    echo "missing lib: $1" && exit 1
 }
 
 assert_version() {
-    if ! pkg-config "--atleast-version=$2" "$1"; then
-        echo "need $1 $2, have `pkg-config --modversion $1`"
-        exit 1
-    fi
-    return 0
+    pkg-config "--atleast-version=$2" "$1" && return 0
+    echo "need $1 $2, have `pkg-config --modversion $1`" && exit 1
 }
 
 have_file() {
     echo -n "checking for $1 ... "
-    if test -e "$1"; then
-        echo "yes"
-        return 0
-    fi
-    echo "no"
-    return 1
+    test -e "$1" && echo "yes" && return 0
+    echo "no" && return 1
 }
 
 have_exe() {
     echo -n "checking for $1 ... "
     which $1 >/dev/null 2>/dev/null
-    if test $? -ne 0; then
-        echo "no"
-        return 1
-    fi
-    echo "yes"
-    return 0
+    test $? -ne 0 && echo "no" && return 1
+    echo "yes" && return 0
 }
 
 assert_exe() {
-   if ! have_exe $1; then
-       echo "missing: $1"
-       exit 1
-   fi
+   have_exe $1 && return 0
+   echo "missing: $1" && exit 1
+}
+
+have_cpuflag() {
+    echo -n "checking for $1 ... "
+    grep -q $1 "/proc/cpuinfo" 2>/dev/null
+    test $? -ne 0 && echo "no" && return 1
+    echo "yes" && return 0
 }
 
 ask() {
